### ISSUE TITLE
Soft switch BOM doesn't display properly

### ISSUE THREAD

**Issue by baldrick1** [btb/80ColumnCard#1]
It appears you uploaded an html file for the soft switch BOM that's interactive.  But Github tries to display it as Raw HTML in its ecosystem.  Downloading the html file and opening it locally doesn't link to the actual data on the web.

**Comment by btb** [comment]
Thanks for pointing that out. It is viewable through github.io, or it would have been if there wasn't a merge error in the file. It's now working at https://btb.github.io/80ColumnCard/hardware/SoftSwitch/bom/
