### ISSUE TITLE
Which bin files get written to which EPROM?

### ISSUE THREAD

**Issue by Mochatea396** [btb/80ColumnCard#2]
I'm ready to program the two EPROMs on the card. I see directories with plenty of bin files but nowhere can I find which bin files I need to put on which EPROM. Some documentation on this project would have been helpful. At least SOME.
Thank you

**Comment by btb** [comment]
The firmware goes on U3 (you probably want "Videx Videoterm ROM 2.4.bin") and the character set goes on U20.

You can put both the standard (i.e. "videx std 7x9 - top right.bin" and alternative character set (I think "videx inverse - top left.bin" would be one most commonly used) on the same EPROM, with the standard character set first.

**Comment by btb** [comment]
added some more detail at https://github.com/btb/80ColumnCard/wiki/Parts

**Comment by Mochatea396** [comment]
Thank you. Excuse my tardy response.

**Comment by btb** [comment]
no problem, you're welcome
